# Generated by Django 3.0.6 on 2020-05-28 14:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blogas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='el.pastas')),
                ('time', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Sukurta')),
                ('text', tinymce.models.HTMLField(max_length=500, null=True, verbose_name='Komentaras')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Vardas')),
                ('blog_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_blogas.Field')),
            ],
        ),
    ]
